# Generated by Django 5.1.4 on 2025-09-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_price_amount_orderitem_price_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
